### ISSUE TITLE
Differentiate between a single and multi-select

### ISSUE THREAD

**Issue by slcp** [shvetsgroup/jquery.multisortable#2]
It is currently not possible to sort a single item via click & drag a la sortable(). A single item must be selected first and moved subsequently in two separate operations.

Perhaps multiselect should evaluate mouseup/mousedown events to differentiate between the two use cases.

**Comment by iamvery** [comment]
Thanks for the idea, it has certainly been noted before. For now, I am not actively maintaining this project, but I'm happy to entertain any pull requests! If this ever comes up in my use, and I modify the code, I will definitely let you know :)

**Comment by slcp** [comment]
I have made some progress with this but it is a bit buggy. Not sure what best practice is with this...should I issue a pull request with a dveleopment branch? Im not overly familiar with git/github workflows :)

**Comment by iamvery** [comment]
Sounds great. I'm not super hip on this side of the process either, but that sounds like a good plan.

**Comment by nickelodeon** [comment]
My recent pull request allows click & drag for single items. I've also got some code in my production version that adds a class to the parent to set different placeholder CSS, depending on whether the event is single or multiple, although I didn't include it in my recent pull request. I'm happy to pass it on if desired :)

**Comment by neochief** [comment]
This issue does not longer exist in latest version of plugin.

@nickelodeon, you're welcome to send a PR, but make sure you merged them to the new code.
