### ISSUE TITLE
on click of any of the selected item : reset others..

### ISSUE THREAD

**Issue by Seabizkit** [shvetsgroup/jquery.multisortable#9]
Hi

Select 2, then click on one of the selected ones, the other selected one should de-select... same if you had 4 selected... then clicking on one of the already selected... should deselect all but the one you just selected.

This should be simple change considering all the other awesome work that you have done.. so far... please update the Master download to the latest version the one that works of "mousedown" and not "click".... this is working awesome-ly for me so far... just what i needed!!! ;-) 

ill give more feed back so i use it more.... just testing the concept...

**Comment by neochief** [comment]
Issue is fixed in https://github.com/shvetsgroup/jquery.multisortable

**Comment by Seabizkit** [comment]
This should be reopened... this is not working even on your demo....

**Comment by Seabizkit** [comment]
May I suggest that you rewrite this and expose "mouse down" and "mouse up"... you have must greater control.

I can submit my rugged hack of your previous version to show how i got the detection of the write bits working.

**Comment by Seabizkit** [comment]
please expose these mouse down and mouse up when/if you rewire it.
